packages:
  - "apps/*"
  - "packages/*"

confirmModulesPurge: false

overrides:
  ws: 8.21.0
  'undici@>=7.0.0 <7.29.1': 7.29.1

allowBuilds:
  "@reown/appkit": false
  bufferutil: false
  esbuild: true
  keccak: false
  unrs-resolver: true
  utf-8-validate: false
  workerd: true
