import Link from "next/link";
import { ArrowRight, Check, ChevronRight, Globe2, LockKeyhole, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { Brand } from "@/components/brand";
import { ThemeToggle } from "@/components/theme-toggle";

export default function MarketingPage() {
  return (
    <div className="marketingPage">
      <header className="marketingHeader"><Brand /><nav><a href="#principles">Principles</a><a href="#product">Product</a><Link href="/docs">Documentation</Link></nav><div className="marketingActions"><ThemeToggle /><Link className="button dark" href="/app">Open Aurel <ArrowRight size={15} /></Link></div></header>
      <main>
        <section className="marketingHero">
          <div className="heroCopy"><p className="eyebrow">Private digital wealth</p><h1>Your onchain wealth,<br /><em>usable everywhere.</em></h1><p>Receive, grow, and use digital wealth through one clear relationship—while you retain control.</p><div className="heroButtons"><Link className="button dark large" href="/app">Open Aurel <ArrowRight size={16} /></Link><Link className="button textButton" href="/docs">How it works <ChevronRight size={16} /></Link></div><div className="trustLine"><span><ShieldCheck size={15} /> Customer-controlled</span><span><LockKeyhole size={15} /> No house token</span><span><Globe2 size={15} /> Globally minded</span></div></div>
          <div className="heroVisual"><div className="visualHalo" /><div className="statementCard"><div className="statementHead"><span>AUREL / PRIVATE</span><span>ILLUSTRATIVE INTERFACE</span></div><p>TOTAL RELATIONSHIP VALUE</p><strong>$184,290.42</strong><div className="statementRule" /><div className="statementRows"><span><i className="dot greenDot" />Productive stablecoins <b>61.2%</b></span><span><i className="dot brassDot" />Connected assets <b>23.4%</b></span><span><i className="dot blueDot" />Liquid reserve <b>15.4%</b></span></div><div className="statementFoot"><span>NET YIELD<br /><b>4.72%</b></span><span>SPENDABLE<br /><b>$28,450</b></span></div></div><div className="floatingNote safetyNote"><ShieldCheck size={17} /><span><small>SAFETY POSTURE</small><strong>Balanced</strong></span></div><div className="floatingNote policyNote"><Sparkles size={17} /><span><small>ACTIVE POLICY</small><strong>Maintain $10K reserve</strong></span></div></div>
        </section>

        <section className="principlesSection" id="principles"><p className="eyebrow">Our position</p><div className="principlesIntro"><h2>Independent by design.<br />Aligned by construction.</h2><p>No proprietary token or forced ecosystem. Decisions begin with your liquidity, risk, and objectives.</p></div><div className="principleGrid"><article><span>01</span><h3>Control stays visible</h3><p>See who controls an asset, what permissions exist, and how to exit.</p></article><article><span>02</span><h3>Risk belongs in context</h3><p>Custody, liquidity, counterparties, and net return appear where you decide.</p></article><article><span>03</span><h3>Liquidity has a purpose</h3><p>Keep what you need available. Put the remainder to transparent work.</p></article></div></section>

        <section className="productSection" id="product"><div className="sectionCopy"><p className="eyebrow">One relationship</p><h2>Built for the way wealth moves now.</h2><p>Connect wallets, move digital dollars, and allocate capital without learning the infrastructure underneath.</p><ul><li><Check size={15} /> Customer-controlled wallet</li><li><Check size={15} /> Cross-chain stablecoin movement</li><li><Check size={15} /> Explained DeFi access</li><li><Check size={15} /> Banking and card rails planned</li></ul></div><div className="productTiles"><article className="productTile mainTile"><span><WalletCards size={20} /></span><p className="eyebrow">Illustrative holdings</p><h3>Everything you own,<br />understood in one place.</h3><div className="miniAssets"><span><i>U</i> USD Coin <b>$141,290</b></span><span><i>E</i> Ether <b>$34,546</b></span><span><i>W</i> Wrapped Ether <b>$8,454</b></span></div></article><article className="productTile quoteTile"><blockquote>Clarity is the first form of security.</blockquote><p>Custody, liquidity, dependencies, and loss conditions travel with every position.</p></article></div></section>
      </main>
      <footer className="marketingFooter"><Brand compact /><p>Wallet and selected protocol features are live on mainnet. Banking, card, insurance, and securities services are not currently offered.</p><div><Link href="/docs">Documentation</Link><a href="/design-system.html">Design system</a><Link href="/app/security">Security</Link></div></footer>
    </div>
  );
}
