import Link from "next/link";
import { ArrowRight, Check, ChevronRight, Globe2, LockKeyhole, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { Brand } from "@/components/brand";
import { ThemeToggle } from "@/components/theme-toggle";

export default function MarketingPage() {
  return (
    <div className="marketingPage">
      <header className="marketingHeader"><Brand /><nav><a href="#principles">Principles</a><a href="#product">Product</a><Link href="/docs">Documentation</Link></nav><div className="marketingActions"><ThemeToggle /><Link className="button dark" href="/app">Open Aurel <ArrowRight size={15} /></Link></div></header>
      <main>
        <section className="marketingHero">
          <div className="heroCopy"><p className="eyebrow">PRIVATE DIGITAL WEALTH</p><h1>Your onchain wealth,<br /><em>usable everywhere.</em></h1><p>A secure financial operating system for receiving, growing, spending, and understanding digital wealth—without surrendering control.</p><div className="heroButtons"><Link className="button dark large" href="/app">Explore the product <ArrowRight size={16} /></Link><Link className="button textButton" href="/docs">Read our principles <ChevronRight size={16} /></Link></div><div className="trustLine"><span><ShieldCheck size={15} /> Noncustodial by default</span><span><LockKeyhole size={15} /> No house token</span><span><Globe2 size={15} /> Built for global lives</span></div></div>
          <div className="heroVisual"><div className="visualHalo" /><div className="statementCard"><div className="statementHead"><span>AUREL / PRIVATE</span><span>ILLUSTRATIVE INTERFACE</span></div><p>TOTAL RELATIONSHIP VALUE</p><strong>$184,290.42</strong><div className="statementRule" /><div className="statementRows"><span><i className="dot greenDot" />Productive stablecoins <b>61.2%</b></span><span><i className="dot brassDot" />Connected assets <b>23.4%</b></span><span><i className="dot blueDot" />Liquid reserve <b>15.4%</b></span></div><div className="statementFoot"><span>NET YIELD<br /><b>4.72%</b></span><span>SPENDABLE<br /><b>$28,450</b></span></div></div><div className="floatingNote safetyNote"><ShieldCheck size={17} /><span><small>SAFETY POSTURE</small><strong>Balanced</strong></span></div><div className="floatingNote policyNote"><Sparkles size={17} /><span><small>ACTIVE POLICY</small><strong>Maintain $10K reserve</strong></span></div></div>
        </section>

        <section className="principlesSection" id="principles"><p className="eyebrow">BUILT DIFFERENTLY</p><div className="principlesIntro"><h2>Independent by design.<br />Aligned by construction.</h2><p>No proprietary token. No forced ecosystem. No hidden preference for the product that pays us most. Every recommendation begins with your liquidity, risk, and objectives.</p></div><div className="principleGrid"><article><span>01</span><h3>Control remains visible</h3><p>Understand who controls every asset, which permissions exist, and how to exit before committing funds.</p></article><article><span>02</span><h3>Safety is not a footnote</h3><p>Counterparties, liquidity, contracts, concentration, and net return are part of every product screen.</p></article><article><span>03</span><h3>Productive until needed</h3><p>Choose how much remains immediately available and how much works in transparent onchain strategies.</p></article></div></section>

        <section className="productSection" id="product"><div className="sectionCopy"><p className="eyebrow">ONE COHERENT RELATIONSHIP</p><h2>Built for the way wealth moves now.</h2><p>Receive digital dollars, connect existing wallets, allocate capital, and understand complex infrastructure through a calm, explicit interface.</p><ul><li><Check size={15} /> Customer-controlled embedded wallet</li><li><Check size={15} /> Mainnet and cross-chain stablecoin flows</li><li><Check size={15} /> Curated, explained DeFi access</li><li><Check size={15} /> Regulated rails and card program planned</li></ul></div><div className="productTiles"><article className="productTile mainTile"><span><WalletCards size={20} /></span><p className="eyebrow">ILLUSTRATIVE BALANCE SHEET</p><h3>Everything you own,<br />understood in one place.</h3><div className="miniAssets"><span><i>U</i> USD Coin <b>$141,290</b></span><span><i>E</i> Ether <b>$34,546</b></span><span><i>W</i> Wrapped Ether <b>$8,454</b></span></div></article><article className="productTile quoteTile"><blockquote>“Clarity is the first form of security.”</blockquote><p>Every position should include its custody, liquidity, dependencies, and plain-language loss conditions.</p></article></div></section>
      </main>
      <footer className="marketingFooter"><Brand compact /><p>Wallet and selected protocol features are live on mainnet. Banking, card, insurance, and securities services are not currently offered.</p><div><Link href="/docs">Documentation</Link><Link href="/app/security">Security</Link></div></footer>
    </div>
  );
}
