"use client";

import { usePrivy } from "@privy-io/react-auth";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Flag, KeyRound, Users } from "lucide-react";
import { FormEvent, useState } from "react";

type BetaData = { mode: string; invites: Array<{ label: string; cohort: string; status: string; max_redemptions: number; redemption_count: number; expires_at?: string }>; cohorts: Array<{ cohort: string; status: string; count: number }> };
type FlagData = { flags: Array<{ flag_key: string; enabled: number; audience: string; updated_at: string }> };
type AnalyticsData = { customers: { total?: number; new_30d?: number }; events: Array<{ event_name: string; events: number; customers: number }>; transactions: Array<{ status: string; count: number }>; support: Array<{ status: string; priority: string; count: number }>; feedback: Array<{ sentiment: string; category: string; count: number }> };

export function BetaOperations() {
  const { getAccessToken } = usePrivy();
  const client = useQueryClient();
  const [label, setLabel] = useState("Founding customer"); const [cohort, setCohort] = useState("founding-01"); const [latestCode, setLatestCode] = useState("");
  async function authFetch(path: string, init?: RequestInit) { const token = await getAccessToken(); return fetch(path, { ...init, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init?.headers ?? {}) }, cache: "no-store" }); }
  const beta = useQuery<BetaData>({ queryKey: ["ops-beta"], queryFn: async () => { const response = await authFetch("/api/ops/beta"); if (!response.ok) throw new Error(); return response.json(); } });
  const flags = useQuery<FlagData>({ queryKey: ["ops-flags"], queryFn: async () => { const response = await authFetch("/api/ops/features"); if (!response.ok) throw new Error(); return response.json(); } });
  const analytics = useQuery<AnalyticsData>({ queryKey: ["ops-analytics"], queryFn: async () => { const response = await authFetch("/api/ops/analytics"); if (!response.ok) throw new Error(); return response.json(); } });
  async function createInvite(event: FormEvent) { event.preventDefault(); const response = await authFetch("/api/ops/beta", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, cohort, maxRedemptions: 1, allowedCountries: [] }) }); const body = await response.json() as { code?: string }; if (response.ok && body.code) { setLatestCode(body.code); await client.invalidateQueries({ queryKey: ["ops-beta"] }); } }
  async function toggleFlag(key: string, enabled: boolean, audience: string) { await authFetch("/api/ops/features", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key, enabled, audience }) }); await client.invalidateQueries({ queryKey: ["ops-flags"] }); }
  if (beta.isError || flags.isError || analytics.isError) return null;
  return <div className="betaOperations"><section className="panel opsAnalytics"><div className="panelHeading"><div><p className="eyebrow">PRIVATE BETA · 30 DAYS</p><h2>Customer and product signals</h2></div><Users size={19} /></div><div className="opsMetrics compact"><div><span>Customers</span><strong>{analytics.data?.customers.total ?? 0}</strong><small>{analytics.data?.customers.new_30d ?? 0} new</small></div><div><span>Submitted</span><strong>{analytics.data?.transactions.find((item) => item.status === "submitted")?.count ?? 0}</strong><small>transaction intents</small></div><div><span>Confirmed</span><strong>{analytics.data?.transactions.find((item) => item.status === "confirmed")?.count ?? 0}</strong><small>source receipts</small></div><div><span>Support</span><strong>{analytics.data?.support.reduce((sum, item) => sum + Number(item.count), 0) ?? 0}</strong><small>cases opened</small></div></div></section><section className="panel inviteManager"><div className="panelHeading"><div><p className="eyebrow">COHORTS · MODE {beta.data?.mode ?? "—"}</p><h2>Issue an invitation</h2></div><KeyRound size={19} /></div><form onSubmit={(event) => void createInvite(event)}><input value={label} onChange={(event) => setLabel(event.target.value)} aria-label="Invitation label" /><input value={cohort} onChange={(event) => setCohort(event.target.value.toLowerCase())} aria-label="Cohort" /><button className="button secondary">Create one-use code</button></form>{latestCode && <div className="issuedCode"><strong>{latestCode}</strong><small>Copy now. Only its hash is stored.</small></div>}<div className="inviteList">{beta.data?.invites.map((invite) => <div key={`${invite.cohort}-${invite.label}`}><span><strong>{invite.label}</strong><small>{invite.cohort}</small></span><b>{invite.redemption_count}/{invite.max_redemptions}</b></div>)}</div></section><section className="panel flagManager"><div className="panelHeading"><div><p className="eyebrow">KILL SWITCHES</p><h2>Feature availability</h2></div><Flag size={19} /></div>{flags.data?.flags.map((flag) => <div className="flagRow" key={flag.flag_key}><span><strong>{flag.flag_key.replaceAll("_", " ")}</strong><small>{flag.audience} · {new Date(flag.updated_at).toLocaleString()}</small></span><button className={`settingsToggle ${flag.enabled ? "active" : ""}`} onClick={() => void toggleFlag(flag.flag_key, !flag.enabled, flag.audience)}>{flag.enabled ? "On" : "Off"}</button></div>)}</section></div>;
}

