"use client";

import { usePrivy } from "@privy-io/react-auth";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Database, LoaderCircle, RefreshCw, Webhook } from "lucide-react";
import { useState } from "react";

type Summary = { intents: Array<{ status: string; count: number }>; webhooks: Array<{ status: string; count: number }>; issues: Array<{ issue_id: string; issue_type: string; severity: string; source_name: string; summary: string; status: string; opened_at: string }>; projections: { count?: number; latest?: string | null }; observedAt: string };

export function OperationsWorkspace() {
  const { getAccessToken, user } = usePrivy();
  const [running, setRunning] = useState(false);
  const [updating, setUpdating] = useState<string | null>(null);
  const query = useQuery<Summary>({ queryKey: ["operations", user?.id], queryFn: async () => { const token = await getAccessToken(); const response = await fetch("/api/ops/summary", { headers: token ? { Authorization: `Bearer ${token}` } : undefined, cache: "no-store" }); const body = await response.json() as Summary & { message?: string }; if (!response.ok) throw new Error(body.message ?? "Operations data is unavailable."); return body; }, enabled: Boolean(user), refetchInterval: 30_000, retry: false });
  async function reconcile() { setRunning(true); try { const token = await getAccessToken(); const response = await fetch("/api/ops/reconcile", { method: "POST", headers: token ? { Authorization: `Bearer ${token}` } : undefined }); if (!response.ok) throw new Error("Reconciliation could not run."); await query.refetch(); } finally { setRunning(false); } }
  async function updateIssue(issueId: string, status: "acknowledged" | "resolved") { setUpdating(issueId); try { const token = await getAccessToken(); const response = await fetch(`/api/ops/issues/${issueId}`, { method: "PATCH", headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error("Issue update failed."); await query.refetch(); } finally { setUpdating(null); } }
  if (query.isPending) return <section className="panel emptyState"><LoaderCircle className="spin" size={19} /><strong>Verifying operations access</strong></section>;
  if (query.isError) return <section className="panel opsDenied"><AlertTriangle size={21} /><h2>Restricted operations surface</h2><p>{query.error.message}</p><small>Set ADMIN_PRIVY_SUBJECTS to an explicit comma-separated allowlist. An empty configuration denies everyone.</small></section>;
  const data = query.data;
  return <><div className="opsMetrics"><article className="panel"><Webhook size={18} /><span>Provider events</span><strong>{data.webhooks.reduce((sum, item) => sum + item.count, 0)}</strong><small>{data.webhooks.map((item) => `${item.status}: ${item.count}`).join(" · ") || "No receipts"}</small></article><article className="panel"><Database size={18} /><span>Policy intents</span><strong>{data.intents.reduce((sum, item) => sum + item.count, 0)}</strong><small>{data.intents.map((item) => `${item.status}: ${item.count}`).join(" · ") || "No intents"}</small></article><article className="panel"><AlertTriangle size={18} /><span>Open issues</span><strong>{data.issues.length}</strong><small>Explicit triage queue</small></article></div><section className="panel opsQueue"><div className="panelHeading"><div><p className="eyebrow">RECONCILIATION</p><h2>Exceptions, not balances</h2><p className="sourceCaption">This console finds gaps between operational projections. Provider and chain records remain authoritative.</p></div><button className="button secondary" disabled={running} onClick={() => void reconcile()}>{running ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />} Run reconciliation</button></div>{data.issues.length ? <div className="opsIssueList">{data.issues.map((issue) => <div key={issue.issue_id}><span className={`statusBadge ${issue.severity === "high" ? "warning" : "neutral"}`}>{issue.severity}</span><div><strong>{issue.summary}</strong><small>{issue.source_name} · {issue.issue_type} · {new Date(issue.opened_at).toLocaleString()}</small></div><div className="opsActions">{issue.status === "open" && <button disabled={updating === issue.issue_id} onClick={() => void updateIssue(issue.issue_id, "acknowledged")}>Acknowledge</button>}<button disabled={updating === issue.issue_id} onClick={() => void updateIssue(issue.issue_id, "resolved")}>Resolve</button></div></div>)}</div> : <div className="emptyState">No open reconciliation exceptions.</div>}</section></>;
}
